<?php

declare(strict_types=1);

namespace Database\Seeders;

use App\Models\Category;
use App\Models\ClassSection;
use App\Models\Parents;
use App\Models\SessionYear;
use App\Models\Students;
use App\Models\StudentSessions;
use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Carbon;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Schema;
use Spatie\Permission\Models\Role;

/**
 * Seeds a fully registered student with:
 *   - A User account (Student role)
 *   - A Students record (qr_token auto-generated via model boot)
 *   - A StudentSessions record for the active session year
 *   - A fees_paids record marking registration payment as successful
 *   - A guardian/parent record linked to the student
 *
 * Credentials:  qrstudent@gmail.com / qrstudent123
 * GR Number:    auto-assigned
 */
class RegisteredStudentWithQrSeeder extends Seeder
{
    public function run(): void
    {
        $studentRole = Role::firstOrCreate(
            ['name' => 'Student', 'guard_name' => 'web'],
        );

        $parentRole = Role::firstOrCreate(
            ['name' => 'Parent', 'guard_name' => 'web'],
        );

        $sessionYear = SessionYear::query()->where('default', 1)->first()
            ?? SessionYear::query()->latest('id')->firstOrFail();

        $classSection = ClassSection::query()->with('class')->first();
        $category = Category::query()->first();

        if (! $classSection || ! $category) {
            $this->command->warn('No class section or category found. Run ClassSeeder first.');

            return;
        }

        // ── Guardian (Parent) user ───────────────────────────────────────────
        $guardianUser = User::withTrashed()->firstOrNew(['email' => 'qrguardian@gmail.com']);
        $guardianUser->forceFill([
            'first_name' => 'QR',
            'last_name' => 'Guardian',
            'password' => Hash::make('qrguardian123'),
            'gender' => 'Male',
            'image' => 'parents/user.png',
            'mobile' => '9876543210',
            'status' => 1,
        ])->save();

        if (method_exists($guardianUser, 'trashed') && $guardianUser->trashed()) {
            $guardianUser->restore();
        }

        $guardianUser->syncRoles([$parentRole->name]);

        $guardian = null;
        if (Schema::hasTable('parents')) {
            $guardian = Parents::updateOrCreate(
                ['user_id' => $guardianUser->id],
                array_intersect_key([
                    'first_name' => 'QR',
                    'last_name' => 'Guardian',
                    'email' => 'qrguardian@gmail.com',
                    'mobile' => '9876543210',
                    'occupation' => 'Engineer',
                    'gender' => 'Male',
                    'dynamic_fields' => '[]',
                    'image' => 'parents/user.png',
                ], array_flip(Schema::getColumnListing('parents')))
            );
        }

        // ── Student user ──────────────────────────────────────────────────────
        $studentUser = User::withTrashed()->firstOrNew(['email' => 'qrstudent@gmail.com']);
        $studentUser->forceFill([
            'first_name' => 'QR',
            'last_name' => 'Student',
            'password' => Hash::make('qrstudent123'),
            'gender' => 'Female',
            'image' => 'students/user.png',
            'mobile' => '9876543211',
            'status' => 1,
            'current_address' => '123 School Lane',
            'permanent_address' => '123 School Lane',
        ])->save();

        if (method_exists($studentUser, 'trashed') && $studentUser->trashed()) {
            $studentUser->restore();
        }

        $studentUser->syncRoles([$studentRole->name]);

        // ── Student profile (qr_token is auto-generated by Students::boot) ───
        $admissionNo = sprintf('STD-%04d', $studentUser->id);
        $rollNumber = ((int) Students::max('roll_number')) + 1;

        $studentData = array_intersect_key([
            'class_section_id' => $classSection->id,
            'category_id' => $category->id,
            'admission_no' => $admissionNo,
            'roll_number' => $rollNumber,
            'caste' => 'General',
            'religion' => 'None',
            'admission_date' => Carbon::today(),
            'blood_group' => 'O+',
            'height' => '160',
            'weight' => '50',
            'father_id' => null,
            'mother_id' => null,
            'guardian_id' => $guardian?->id,
            'is_new_admission' => 0,
            'application_type' => 'online',
            'dynamic_fields' => '[]',
        ], array_flip(Schema::getColumnListing('students')));

        $student = Students::updateOrCreate(
            ['user_id' => $studentUser->id],
            $studentData
        );

        // Ensure qr_token is set (updateOrCreate won't trigger boot on update)
        if (empty($student->qr_token)) {
            $student->update(['qr_token' => bin2hex(random_bytes(32))]);
        }

        // ── Session enrollment ────────────────────────────────────────────────
        if (Schema::hasTable('student_sessions')) {
            StudentSessions::updateOrCreate(
                ['student_id' => $student->id, 'session_year_id' => $sessionYear->id],
                array_intersect_key([
                    'class_section_id' => $classSection->id,
                    'previous_session_year_id' => null,
                ], array_flip(Schema::getColumnListing('student_sessions')))
            );
        }

        // ── Registration fees paid (marks payment as successful) ──────────────
        if (Schema::hasTable('fees_paids')) {
            $existing = DB::table('fees_paids')
                ->where('student_id', $student->id)
                ->where('session_year_id', $sessionYear->id)
                ->exists();

            if (! $existing) {
                DB::table('fees_paids')->insert([
                    'student_id' => $student->id,
                    'class_id' => $classSection->class_id,
                    'session_year_id' => $sessionYear->id,
                    'total_amount' => 500.00,
                    'is_fully_paid' => 1,
                    'mode' => 1, // 1 = online
                    'date' => Carbon::today()->toDateString(),
                    'created_at' => now(),
                    'updated_at' => now(),
                ]);
            }
        }

        $this->command->info("Seeded QR student: {$studentUser->email} / qrstudent123");
        $this->command->info("GR Number : {$admissionNo}");
        $this->command->info("QR Token  : {$student->fresh()->qr_token}");
    }
}
